name: Demo Website

on:
  workflow_dispatch:
  push:
    paths:
      - "ShadcnBlazor*/**"
    branches:
      - main

env:
  IMAGE_NAME: shadcnblazor

jobs:
  
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5

      - name: Build image
        run: docker build . --file ShadcnBlazor.Test/Docker/Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.RELEASE_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          
          [[ "$GITHUB_REF" == refs/tags/* ]] && VERSION=$(echo "$VERSION" | sed -e 's/^v//')
          
          [ "$VERSION" == "main" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION